PREFIX :     <http://www.rqtl.org/ns/#> 
PREFIX qb:   <http://purl.org/linked-data/cube#> 
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX prop: <http://www.rqtl.org/dc/properties/> 
PREFIX cs:   <http://www.rqtl.org/dc/cs/>

# IC-11. All dimensions required (modified)

SELECT * WHERE {
    {?obs qb:dataSet/qb:structure/qb:component/qb:componentProperty ?dim }
    UNION
	#also include qb:dimension resources
    {?obs qb:dataSet/qb:structure/qb:component/qb:dimension ?dim }

    ?dim a qb:DimensionProperty;
    FILTER NOT EXISTS { ?obs ?dim [] }
}